### ISSUE TITLE
running role multiple times results in corrupt wp-salts.php

### ISSUE THREAD

**Issue by stevestrutt** [bertvv/ansible-role-wordpress#10]
Running the role multiple times results in a corrupt version of wp-salts.php and wordpress fails to start with a white screen of death and a http status code 500 - internal service error. 
 An additional <?php is inserted at the bottom of the file the second time the role runs. 
<?php
define('AUTH_KEY',         'vn;v:-JWmmh [{/$z  l9Yqb%S-x~&3FotV!c&vdoK&hWVByv#XqNlPqY:U4[:J!');
define('SECURE_AUTH_KEY',  'B;bRti+)(<b.im0ABg|zkB-.9O%_7<0O|B&[&-Siksp7{.n~QK}ea0-4Y}[U]]h)');
define('LOGGED_IN_KEY',    '/?>Tz:!A+e^aP7gL3f9@-FC>EW33m%c[%1s38zmx?+zNFWX5NBYU(,Lg~^kAY.a+');
define('NONCE_KEY',        'D&tT[HfsmHJ`/[V[/LzII-&||wg^aMX<wC}&JJjKS%>ge0BEP_xG}YfRa/V+)6Jm');
define('AUTH_SALT',        'QUXmYn+x-97%Q,1vS&-tBE!=/xK8.2B+eJ-c>{J2(HNd;^.g;A:f3W<TI2CX!a|,');
define('SECURE_AUTH_SALT', 'WOoZ$EupRj})U63]gOkkQj;4*11l9-fBornHl_KcX@o.<%D-ihEF.b)YQtQHL%&h');
define('LOGGED_IN_SALT',   '>nY(|As.>hbi(l=+)*DZVFRX3L3y.I|)lK,Gp-Nx~[6kjQ>OE9HdO9s+4qBZrN,h');
define('NONCE_SALT',       '6S|*pT-O%GP,l%IV!1%tmC~L4mu3!I|g7QW8A<7t|h3,&nO}aOYeC4$95/<(X8#f');
<?php
?>

**Comment by bertvv** [comment]
I've rewritten the playbook, it's now idempotent: the salt will only be downloaded if the file does not exist yet. A new version will be released soon, I'll close the issue after that.

Sorry for the wait!

**Comment by bertvv** [comment]
Is fixed in a2284b4 and 10d0c89
